# Generated by Django 2.0.7 on 2018-07-19 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0002_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commodity',
            old_name='marke_price',
            new_name='market_price',
        ),
    ]
